### ISSUE TITLE
Uncaught TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by yanivdll** [groktools/journal#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.23.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [journal](https://github.com/groktools/journal) package 0.1.1

### Stack Trace

Uncaught TypeError: Path must be a string. Received undefined

```
At path.js:7

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.join (path.js:1211:7)
    at Object.createFileIfNotAlreadyExists (/packages/journal/lib/journal.coffee:60:25)
    at Object.createOrOpen (/packages/journal/lib/journal.coffee:44:6)
    at /packages/journal/lib/journal.coffee:22:88)
    at CommandRegistry.handleCommandEvent (/private/var/folders/35/39kzlnr54fb_1g7s58yv8dc80000gn/T/AppTranslocation/F2B06690-A3A7-48D8-898D-846EFEA42664/d/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at Object.didConfirmSelection (/private/var/folders/35/39kzlnr54fb_1g7s58yv8dc80000gn/T/AppTranslocation/F2B06690-A3A7-48D8-898D-846EFEA42664/d/Atom.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:143:35)
    at SelectListView.confirmSelection (/private/var/folders/35/39kzlnr54fb_1g7s58yv8dc80000gn/T/AppTranslocation/F2B06690-A3A7-48D8-898D-846EFEA42664/d/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:327:26)
    at HTMLDivElement.core:confirm (/private/var/folders/35/39kzlnr54fb_1g7s58yv8dc80000gn/T/AppTranslocation/F2B06690-A3A7-48D8-898D-846EFEA42664/d/Atom.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:84:20)
    at CommandRegistry.handleCommandEvent (/private/var/folders/35/39kzlnr54fb_1g7s58yv8dc80000gn/T/AppTranslocation/F2B06690-A3A7-48D8-898D-846EFEA42664/d/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/private/var/folders/35/39kzlnr54fb_1g7s58yv8dc80000gn/T/AppTranslocation/F2B06690-A3A7-48D8-898D-846EFEA42664/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/private/var/folders/35/39kzlnr54fb_1g7s58yv8dc80000gn/T/AppTranslocation/F2B06690-A3A7-48D8-898D-846EFEA42664/d/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/private/var/folders/35/39kzlnr54fb_1g7s58yv8dc80000gn/T/AppTranslocation/F2B06690-A3A7-48D8-898D-846EFEA42664/d/Atom.app/Contents/Resources/app/src/window-event-handler.js:108:40)
```

### Commands

```
     -2:12.5.0 core:backspace (input.hidden-input)
     -2:11.8.0 core:confirm (input.hidden-input)
     -2:11.8.0 settings-view:install-packages-and-themes (ul.list-inline.tab-bar.inset-panel)
     -2:09.9.0 editor:select-line (div.panels-item)
     -2:07.5.0 core:move-right (button.btn.btn-default.selected)
  2x -2:06.3.0 core:move-down (button.btn.btn-default.selected)
  6x -2:05.6.0 core:move-up (button.btn.btn-default.selected)
     -1:58.1.0 core:confirm (input.hidden-input)
     -0:32.9.0 command-palette:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:30.3.0 core:move-down (input.hidden-input)
     -0:30.1.0 core:confirm (input.hidden-input)
     -0:30.1.0 journal:createOrOpen (ul.list-inline.tab-bar.inset-panel)
     -0:11.2.0 command-palette:toggle (div.panels-item)
     -0:08.4.0 core:move-down (input.hidden-input)
     -0:07.8.0 core:confirm (input.hidden-input)
     -0:07.8.0 journal:createOrOpen (div.panels-item)
```

### Non-Core Packages

```
atomic-emacs 0.12.1 
journal 0.1.1 
```

**Comment by malonehedges** [comment]
@yanivdll Did this happen when clicking a file in the tree view but not fully opening, or something else? Have been playing around with the package and was running into that issue myself.
